server:
  port: 7101
spring:
  application:
    name: ConfigCenter
  cloud:
    config:
      server:
        git:
          uri: ssh://git@47.98.165.84:/home/git/objectcloud-config.git
          username: git
          password: Object971103.
#服务注册配置
eureka:
  client:
    #将客户端注册进注册中心
    service-url:
      #单机版注册
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    #注册中心的链接名（右侧Status）
    instance-id: ${spring.application.name}:${server.port}
    #点到链接名左下角出现IP提示
    prefer-ip-address: true
